package util

import "testing"

func TestGenerateRandomByt(t *testing.T) {
	b, err := GenerateRandomBytes(32)
	if err != nil {
		t.Fatalf("error while generating random bytes: %s", err)
		return
	}

	if len(b) != 32 {
		t.Fatalf("Length of generated bytes is not equal to the given length")
	}
}
