name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        env:
          REDIS_PASSWORD: miau
        options: >
          --requirepass my_redis_password

      postgres:
        image: postgres
        env:
          POSTGRES_DB: fahrtenbuch_db
          POSTGRES_USER: fahrtenbuchmiau_user
          POSTGRES_PASSWORD: fahrtenbuch_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install dependencies
        run: go mod download
        working-directory: server

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Run tests
        env:
          IS_PROD: false
          SERVER_PORT: 8080
          POSTGRES_USER: fahrtenbuchmiau_user
          POSTGRES_HOST: localhost
          POSTGRES_DATABASE: fahrtenbuch_db
          POSTGRES_PASSWORD: fahrtenbuch_password
          POSTGRES_PORT: 5432
          REDIS_ADDR: localhost:6379
          REDIS_PASSWORD: miau
          REDIS_DB: 0
          JwtSecret: sdfhkgbsdkjbgdsjhbgdsfg
        run: go test ./...
        working-directory: server

      - name: Build project
        run: go build -o fahrtenbuch ./...
        working-directory: server
