name: Build and Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: test
  SERVER_PORT: 8080
  ALLOWED_ORIGIN: localhost
  SUPABASE_ANON_PUBLIC_KEY: dev
  SUPABASE_SECRET_KEY: dev
  SUPABASE_JWT_SECRET: dev
  SUPABASE_PROJECT_URL: https://dev.co/
  SUAPBASE_PROJECT_ID: dev

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "node" # this automatically means that the latest node version is being used for testing

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
          POSTGRES_DB: fahrtenbuch_db
          POSTGRES_USER: fahrtenbuchmiau_user
          POSTGRES_PASSWORD: fahrtenbuch_password
          REDIS_ADDR: ${{ env.REDIS_ADDR }}
          REDIS_PASSWORD: ${{ env.REDIS_PASSWORD }}
          REDIS_DB: ${{ env.REDIS_DB }}
          JwtSecret: ${{ env.JwtSecret }}
        run: npm test

      - name: Build project
        run: npm run build
